apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "10"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
    kubernetes.io/ingress.class: alb
  name: ecom-prodapac-ingress
  namespace: ecom-prodapac-backend
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: prod-apac-ecom-glb-prodmedia-svc
            port:
              number: 80
        path: /glb/estore/v1/assets*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: prod-apac-ecom-glb-prodspec-svc
            port:
              number: 80
        path: /glb/estore/v1/product-specs*
        pathType: ImplementationSpecific
